# Generated by Django 4.2 on 2023-04-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('score', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'programer',
            },
        ),
    ]
